# Generated by Django 3.2.9 on 2022-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('price_usd', models.FloatField(blank=True, null=True, verbose_name='Цена в долларах')),
                ('price_rub', models.FloatField(blank=True, null=True, verbose_name='Цена в рублях')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
            },
        ),
    ]
