# Generated by Django 3.2.9 on 2022-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_rename_order_sheet_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата поставки'),
        ),
    ]
